kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "common.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "common.fullname" . }}
    namespace: monitor
roleRef:
  kind: ClusterRole
  name: {{ include "common.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
